'use strict';

/**
 * check-dist.js — runtime-asset validation (Phase 19).
 *
 * Verifies that every runtime-critical file is actually packaged, not just
 * present in the source tree:
 *   1. Electron asar listing (tmp/asar-list.txt, generated by the packaging
 *      step) — main process, renderer, shared contract, adhan audio, fonts.
 *   2. Referenced-asset sweep — every asset referenced from code/config
 *      (adhan sounds in main/adhan-files.js, fonts in styles/fonts.css)
 *      must exist on disk.
 *   3. Web build (www/) — engine bundle exists and exposes the contract;
 *      index.html loads it before app.js.
 *   4. Android assets (android/app/src/main/assets/public) — web shell
 *      present; no references to nonexistent notification sounds.
 *
 * Exits 1 on any missing runtime asset. Sections whose build artifacts do
 * not exist yet are reported and skipped (run after packaging for full coverage).
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
let problems = 0;
const fail = (msg) => { problems++; console.error('  ✗ ' + msg); };
const pass = (msg) => console.log('  ✓ ' + msg);
const exists = (p) => fs.existsSync(path.join(ROOT, p));

console.log('— 1. Electron asar contents —');
const listFile = path.join(ROOT, 'tmp', 'asar-list.txt');
if (!fs.existsSync(listFile)) {
  console.log('  – tmp/asar-list.txt not found (package first: npm run package) — skipped');
} else {
  const lines = fs.readFileSync(listFile, 'utf8')
    .split(/\r?\n/)
    .map((l) => l.replace(/^\\+|^\/+/g, '').replace(/\\/g, '/'))
    .filter(Boolean);
  const need = [
    'package.json', 'prayer-times.html', 'adhan.html', 'widget.html',
    'preload.js', 'widget-preload.js',
    'main/main.js', 'main/scheduler.js', 'main/tray.js', 'main/adhan-files.js', 'main/debug-log.js',
    'main/overlay-preload.js', 'main/json-store.js',
    'shared/pt-engine.js',
    'js/app.js', 'js/pages.js', 'js/pages3.js', 'js/reader.js', 'js/store3.js',
    'js/data.js', 'js/stats.js', 'js/platform.js', 'js/overlay.js', 'js/widget.js', 'js/compass.js',
    'styles/app.css',
    'assets/icon.ico', 'assets/icon-256.png',
    'data/quran.json',
  ];
  // Adhan audio (asarUnpacked): every bundled mp3 must be in the package.
  const adhanDir = path.join(ROOT, 'assets', 'adhans');
  if (fs.existsSync(adhanDir)) {
    for (const f of fs.readdirSync(adhanDir)) {
      if (f.toLowerCase().endsWith('.mp3')) need.push('assets/adhans/' + f);
    }
  }
  // Fonts actually referenced by styles/fonts.css.
  const fontsCss = path.join(ROOT, 'styles', 'fonts.css');
  if (fs.existsSync(fontsCss)) {
    const m = fs.readFileSync(fontsCss, 'utf8').match(/fonts\/[\w.-]+\.woff2/g) || [];
    for (const f of [...new Set(m)]) need.push(f);
  }
  const missing = need.filter((f) => !lines.includes(f));
  if (missing.length) fail('MISSING from app.asar: ' + missing.join(', '));
  else pass(`all ${need.length} required runtime files in app.asar`);
  pass('asar total files: ' + lines.length + ', adhan lib bundled: '
    + (lines.some((l) => l.startsWith('node_modules/adhan/')) ? 'yes' : 'NO'));
  pass('tz-lookup bundled: ' + (lines.some((l) => l.startsWith('node_modules/tz-lookup/')) ? 'yes' : 'NO'));
}

console.log('— 2. Referenced assets exist on disk —');
{
  // main/adhan-files.js maps adhan ids → bundled file names in assets/adhans/.
  if (exists('main/adhan-files.js') && exists('assets/adhans')) {
    const src = fs.readFileSync(path.join(ROOT, 'main', 'adhan-files.js'), 'utf8');
    const names = [...new Set(src.match(/'([\w-]+\.mp3)'/g) || [])].map((s) => s.replace(/'/g, ''));
    const miss = names.filter((n) => !exists('assets/adhans/' + n));
    if (miss.length) fail('adhan audio referenced but missing: ' + miss.join(', '));
    else pass(`${names.length} referenced adhan audio files present (${names.join(', ')})`);
  }
  const fontsCss = path.join(ROOT, 'styles', 'fonts.css');
  if (fs.existsSync(fontsCss)) {
    const refs = [...new Set(fs.readFileSync(fontsCss, 'utf8').match(/fonts\/[\w.-]+\.woff2/g) || [])];
    const miss = refs.filter((r) => !exists(r));
    if (miss.length) fail('fonts referenced but missing: ' + miss.join(', '));
    else pass(`${refs.length} referenced fonts present`);
  }
  const quran = exists('data/quran.json');
  if (quran) {
    try {
      const d = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'quran.json'), 'utf8'));
      (d && d.v === 1 && Array.isArray(d.surahs) && d.surahs.length === 114)
        ? pass('data/quran.json valid (114 surahs)')
        : fail('data/quran.json unexpected shape');
    } catch (e) { fail('data/quran.json unparseable: ' + e.message); }
  } else fail('data/quran.json missing');
}

console.log('— 3. Web build (www/) —');
if (!exists('www/index.html')) {
  console.log('  – www/ not built (npm run www) — skipped');
} else {
  const idx = fs.readFileSync(path.join(ROOT, 'www', 'index.html'), 'utf8');
  exists('www/js/adhan-bundle.js')
    ? pass('www/js/adhan-bundle.js present')
    : fail('www/js/adhan-bundle.js missing');
  if (exists('www/js/adhan-bundle.js')) {
    const bundle = fs.readFileSync(path.join(ROOT, 'www', 'js', 'adhan-bundle.js'), 'utf8');
    bundle.includes('__ptAdhan')
      ? pass('adhan-bundle exposes the calculation engine (__ptAdhan)')
      : fail('adhan-bundle does NOT expose __ptAdhan');
    bundle.includes('ptMobile')
      ? pass('adhan-bundle carries the mobile scheduler (ptMobile)')
      : fail('adhan-bundle missing ptMobile');
  }
  exists('www/js/pt-engine.js')
    ? pass('www/js/pt-engine.js (shared contract) present')
    : fail('www/js/pt-engine.js missing');
  const iEngine = idx.indexOf('js/pt-engine.js');
  const iApp = idx.indexOf('js/app.js');
  const iBundle = idx.indexOf('js/adhan-bundle.js');
  (iEngine !== -1 && iApp !== -1 && iEngine < iApp)
    ? pass('index.html loads the contract before app.js')
    : fail('index.html contract/app.js order wrong');
  (iBundle !== -1 && iBundle > iApp)
    ? pass('index.html loads the engine bundle (engineReady bridges it)')
    : fail('index.html missing adhan-bundle.js');
  for (const f of ['js/platform.js', 'js/compass.js', 'js/overlay.js', 'js/widget.js', 'data/quran.json']) {
    exists('www/' + f) ? pass('www/' + f + ' present') : fail('www/' + f + ' missing');
  }
}

console.log('— 4. Android assets —');
const androidPublic = path.join(ROOT, 'android', 'app', 'src', 'main', 'assets', 'public');
if (!fs.existsSync(androidPublic)) {
  console.log('  – android assets not synced (npx cap sync android) — skipped');
} else {
  fs.existsSync(path.join(androidPublic, 'index.html'))
    ? pass('android web shell present (assets/public/index.html)')
    : fail('android web shell missing — run npx cap sync android');
  const aBundle = path.join(androidPublic, 'js', 'adhan-bundle.js');
  if (fs.existsSync(aBundle)) {
    const src = fs.readFileSync(aBundle, 'utf8');
    src.includes('notifsound')
      ? fail('android bundle references notifsound (nonexistent resource)')
      : pass('no nonexistent notification-sound reference in android bundle');
    src.includes('__ptAdhan')
      ? pass('android bundle exposes the calculation engine')
      : fail('android bundle missing __ptAdhan');
  } else {
    console.log('  – android adhan-bundle not synced yet — skipped');
  }
  const aEngine = path.join(androidPublic, 'js', 'pt-engine.js');
  fs.existsSync(aEngine)
    ? pass('android shared contract synced')
    : console.log('  – android pt-engine.js not synced yet (cap sync) — skipped');
}

console.log('');
if (problems) {
  console.error(`${problems} problem(s) found — build artifacts incomplete`);
  process.exit(1);
}
console.log('Runtime asset validation passed ✓');
